name: Release Manual con Versión

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.11"

      - name: Instalar UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl || sudo apt-get install -y upx

      - name: Compilar para Linux y Windows
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          LDFLAGS="-s -w -X main.version=${VERSION}"

          # Linux
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
            go build -trimpath -ldflags="$LDFLAGS" \
            -o sic-linux-amd64 \
            cmd/sic/main.go

          # Windows
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 \
            go build -trimpath -ldflags="$LDFLAGS" \
            -o sic-windows-amd64.exe \
            cmd/sic/main.go

      - name: Comprimir binarios con UPX
        run: |
          upx --best --lzma sic-linux-amd64
          upx --best --lzma sic-windows-amd64.exe

      - name: Mostrar tamaño de los binarios
        run: |
          ls -lh sic-linux-amd64 sic-windows-amd64.exe

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sic-linux-amd64
            sic-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
